Item.create!(name:"u",rank:"C",user_id:1)
Item.create!(name:"s",rank:"E",user_id:2)
Item.create!(name:"e",rank:"A",user_id:3)
Item.create!(name:"o",rank:"B",user_id:4)
Item.create!(name:"y",rank:"B",user_id:5)
Item.create!(name:"k",rank:"E",user_id:6)
Item.create!(name:"t",rank:"C",user_id:7)